### ISSUE TITLE
Extract the document from the URL

### ISSUE THREAD

**Issue by acDante** [amazon-science/ccsum#2]
Hi, I am trying to reproduce your datasets by extracting the text from URL with newsplease API (using the version of CCSum dataset on Huggingface). However, I find there are some advertisements or other irrelevant texts in the extracted content. Do you have some existing code snippets for extracting and filtering the web text?

**Comment by xiangjjj** [comment]
hi, Our focus was on making sure the summary do not focus on minor details of the article (ads or irrelevant texts), and we did not post-process the extracted main_content from the news articles.
